### ISSUE TITLE
getAnyOption(0) on SELECT AVG(column1) FROM table1 always return None

### ISSUE THREAD

**Issue by golem131** [finagle/finagle-postgres#47] opened 2016-12-15 21:19 UTC
in sum, max etc same behavior (((

**Comment by jeremyrsmith** [comment] 2017-03-07 22:30
@golem131 could you make a PR with a (failing) test that demonstrates the problem?

**Comment by leonmaia** [comment] 2019-06-06 18:50
Since we could not reproduce this I'll be closing this issue.

**Closed as completed by leonmaia** 2019-06-06 18:50 UTC
